server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: never

#SPRING_WEBFLUX_BASE_PATH=/api

spring:
  redis:
    database: 0
    host: "localhost"
    port: 6379
    timeout: 60000

integration:
  stock:
    url: "https://statusinvest.com.br"
    authority: "statusinvest.com.br"
    referer: "https://statusinvest.com.br/"
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
